//JS Quiz Questions
var questions = [
    {
        "Question": "Inside which HTML element do we put the JavaScript?",
        "option1": "<script>",
        "option2": "<div>",
        "option3": "<body>",
        "option4": "<style>",
        "answer": "1",
    },
    {
        "Question": "Is Javascript the same as Java?",
        "option1": "True",
        "option2": "False",
        "option3": "Both",
        "option4": "Either or",
        "answer": "1",
    },
    {
        "Question": "What language defines the behavior of a webpage?",
        "option1": "XML",
        "option2": "HTML",
        "option3": "JavaScript",
        "option4": "CSS",
        "answer": "3",
    },
    {
        "Question": "What is the correct way to write a JavaScript Array?",
        "option1": "var colors = 'red', 'violet', 'blue'",
        "option2": "var colors = ['red', 'violet', 'blue']",
        "option3": "var colors = ['red[0]', 'violet[1]', 'blue[2]']",
        "option4": "var colors = ('red', 'violet', 'blue')",
        "answer": "2",
    },
    {
        "Question": "Inorder to assign a value to a variable which should you use?",
        "option1": "x",
        "option2": "*",
        "option3": "=",
        "option4": "()",
        "answer": "3",

    },
    {
        "Question": "How do you write an IF statement?",
        "option1": "if i = 7 else",
        "option2": "if i == 7",
        "option3": "if(i == 7)",
        "option4": "if i = 7 then",
        "answer": "3",

    },
    {
        "Question": "What is the correct syntax for referring to an external script called 'xxxx.js'?",
        "option1": "<script href='xxxx.js'>",
        "option2": "<script src='xxxx.js'>",
        "option3":  "<script type='xxxx.js'>",
        "option4": "<script name='xxxx.js'>",
        "answer": "2",
    },
    {
        "Question": "How do you write 'Hello World!' in an alert box?",
        "option1": "msg('Hello World!')",
        "option2": "alert('Hello World!')",
        "option3": "msgBox('Hello World!')",
        "option4": "alertBox('Hello World!')",
        "answer": "2",
    },
    {
        "Question": "How do you create a function in JavaScript?'?",
        "option1": "function myFunction()",
        "option2": "function: myFunction()",
        "option3": "<function.myFunction()",
        "option4": "function = myFunction()",
        "answer": "4",
        
    },
    {
        "Question": "How does a FOR loop start?",
        "option1": "for (i = 0; i > 7; i++)",
        "option2": "for (i < 7; i++)",
        "option3": "for i = 1 to 7",
        "option4": "for (i = 0; i <=7)",
        "answer": "1",
    }];